# Generated by Django 3.0.3 on 2020-03-03 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200304_0117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='gradge',
            new_name='grage',
        ),
    ]
